application: folioverse
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css))

- url: /data/audio/(.*\.ogg)
  mime_type: application/ogg
  static_files: data/audio/\1
  upload: data/audio/(.*\.ogg)
  
- url: /data/audio/(.*\.mp3)
  mime_type: application/mp3
  static_files: data/audio/\1
  upload: data/audio/(.*\.mp3)
  
- url: .*
  script: main.py
